variables:
  BUILD: beta
  TAG: beta
  ANDROID_BUILD_APK_NAME: apk
  ANDROID_BUILD_APK_ENV: debug

beta-web-build:
  extends: .build
  only:
    - master

beta-web-deploy:
  extends: .deploy
  dependencies:
    - beta-web-build
  only:
    - master

beta-android-build:
  extends: .build-android
  only:
    variables:
      - $ANDROID_KEYSTORE
    refs:
      - master

beta-android-deploy:
  extends: .deploy-android
  dependencies:
    - beta-android-build
  only:
    variables:
      - $ANDROID_KEYSTORE
    refs:
      - master