beta-web-build:
  extends: .build
  variables:
    BUILD: beta
    TAG: beta
  only:
    - master

beta-web-deploy:
  extends: .deploy
  variables:
    TAG: beta
  dependencies:
    - beta-web-build
  only:
    - master
