variables:
  BUILD: prod
  TAG: stable

prod-web-build:
  extends: .prod-build

prod-web-deploy:
  extends: .prod-deploy
  dependencies:
    - prod-web-build
  after_script:
    - docker tag $DOCKER_IMAGE_REPO:$TAG $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG

prod-android-build:
  extends: .prod-build-android

prod-android-deploy:
  extends: .prod-deploy-android
  dependencies:
    - prod-android-build