variables:
  BUILD: prod
  TAG: stable

prod-web-build:
  extends: .build
  only:
    - tags
    - /^release\/\d+\.\d+$/

prod-web-deploy:
  extends: .deploy
  dependencies:
    - prod-web-build
  only:
    - tags
    - /^release\/\d+\.\d+$/
  after_script:
    - docker tag $DOCKER_IMAGE_REPO:$TAG $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG

prod-android-build:
  extends: .build-android
  only:
    - tags
    - /^release\/\d+\.\d+$/

prod-android-deploy:
  extends: .deploy-android
  dependencies:
    - prod-android-build
  only:
    - tags
    - /^release\/\d+\.\d+$/
