prod-web-build:
  extends: .build
  variables:
    BUILD: prod
    TAG: stable
  only:
    - tags

prod-web-deploy:
  extends: .deploy
  variables:
    TAG: stable
  dependencies:
    - prod-web-build
  after_script:
    - docker tag $DOCKER_IMAGE_REPO:$TAG $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
  only:
    - /^release\/\d+\.\d+$/
    - tags

prod-android-build:
  extends: .build-android
  variables:
    BUILD: prod
    TAG: android-stable
    ANDROID_BUILD_APK_ENV: release
  only:
    refs:
      - /^release\/\d+\.\d+$/
      - tags
    variables:
      - $ANDROID_KEYSTORE

prod-android-deploy:
  extends: .deploy-android
  variables:
    BUILD: prod
    ANDROID_BUILD_APK_ENV: release
  dependencies:
    - prod-android-build
  only:
    refs:
      - /^release\/\d+\.\d+$/
      - tags
    variables:
      - $ANDROID_KEYSTORE
