prod-web-build:
  extends: .build
  variables:
    BUILD: prod
    TAG: stable
  only:
    - /^v.*$/

prod-web-deploy:
  extends: .deploy
  variables:
    TAG: stable
  dependencies:
    - prod-web-build
  after_script:
    - docker push $DOCKER_IMAGE_REPO:$TAG
    - docker tag $DOCKER_IMAGE_REPO:$TAG $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
  only:
    - /^v.*$/
