variables:
  BUILD: prod
  TAG: stable

prod-web-build:
  extends: .build
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\/\d+\.\d+$/
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/

prod-web-deploy:
  extends: .deploy
  dependencies:
    - prod-web-build
  after_script:
    - docker tag $DOCKER_IMAGE_REPO:$TAG $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\/\d+\.\d+$/
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/

prod-android-build:
  extends: .build-android
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\/\d+\.\d+$/
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
    - if: $ANDROID_KEYSTORE != null

prod-android-deploy:
  extends: .deploy-android
  dependencies:
    - prod-android-build
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\/\d+\.\d+$/
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
    - if: $ANDROID_KEYSTORE != null
