variables:
  BUILD: prod
  TAG: stable
  ANDROID_BUILD_APK_NAME: app
  ANDROID_BUILD_APK_ENV: release

prod-web-build:
  extends: .build
  only:
    - /^release\/\d+\.\d+$/
    - tags

prod-web-deploy:
  extends: .deploy
  dependencies:
    - prod-web-build
  after_script:
    - docker tag $DOCKER_IMAGE_REPO:$TAG $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
  only:
    - /^release\/\d+\.\d+$/
    - tags

prod-android-build:
  extends: .build-android
  only:
    refs:
      - /^release\/\d+\.\d+$/
      - tags
    variables:
      - $ANDROID_KEYSTORE

prod-android-deploy:
  extends: .deploy-android
  dependencies:
    - prod-android-build
  only:
    refs:
      - /^release\/\d+\.\d+$/
      - tags
    variables:
      - $ANDROID_KEYSTORE