release-build:
  stage: build
  only:
    - tags
    - /^release\/\d+\.\d+$/
  script:
    - docker build . -t $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG --build-arg BUILD=prod --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA
    - docker save $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 day
release-deploy:
  stage: deploy
  dependencies:
    - release-build
  only:
    - tags
    - /^release\/\d+\.\d+$/
  script:
    - docker load < image.tar
    - docker push $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
    - docker tag $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG $DOCKER_IMAGE_REPO:stable
    - docker push $DOCKER_IMAGE_REPO:stable