release:
  stage: release
  image: sentryio/sentry-new-release:0.3.0
  script:
    - sh /usr/bin/pipe.sh
  before_script:
    - echo "Release"
  rules:
    - if: $SENTRY_AUTH_TOKEN != '' && $SENTRY_ORG != '' && $SENTRY_PROJECT != ''