release:
  stage: release
  image:
    name: getsentry/sentry-new-release:0.3.0
    entrypoint: ["/bin/sh", "-c"]
  script:
    - |
      if [[ ! -z $CI_COMMIT_TAG ]]; then
        export ENVIRONMENT=production
      elif [[ $CI_COMMIT_BRANCH = "dev" ]]; then
        export ENVIRONMENT=development
      elif [[ $CI_COMMIT_BRANCH = "master" ]]; then
        export ENVIRONMENT=beta
      else
        export ENVIRONMENT=development
      fi

      export BITBUCKET_COMMIT=$CI_COMMIT_SHA

      if [[ $SENTRY_AUTH_TOKEN != '' && $SENTRY_ORG != '' && $SENTRY_PROJECT != '' ]]; then
        sh /usr/bin/pipe.sh
      fi
  before_script: []
