release:
  stage: release
  image: sentryio/sentry-new-release:0.3.0
  variables:
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    SENTRY_ORG: $SENTRY_ORG
    SENTRY_PROJECT: $SENTRY_PROJECT
  only:
    variables:
      - $SENTRY_AUTH_TOKEN
      - $SENTRY_ORG
      - $SENTRY_PROJECT