test-web-build:
  extends: .build
  variables:
    BUILD: dev
    TAG: latest
  only:
    - dev

test-web-deploy:
  extends: .deploy
  variables:
    TAG: latest
  dependencies:
    - test-web-build
  only:
    - dev

test-android-build:
  extends: .build-android
  variables:
    BUILD: dev
    TAG: android-latest
    ANDROID_BUILD_APK_NAME: apk
    ANDROID_BUILD_APK_ENV: debug
  only:
    refs:
      - dev
    variables:
      - $ANDROID_KEYSTORE

test-android-deploy:
  extends: .deploy-android
  dependencies:
    - test-android-build
  variables:
    ANDROID_BUILD_APK_NAME: apk
    ANDROID_BUILD_APK_ENV: debug
  only:
    refs:
      - dev
    variables:
      - $ANDROID_KEYSTORE

