variables:
  BUILD: test
  TAG: latest
  BRANCH: dev

test-web-build:
  extends: .build

test-web-deploy:
  extends: .deploy
  dependencies:
    - test-web-build

test-android-build:
  extends: .build-android

test-android-deploy:
  extends: .deploy-android
  dependencies:
    - test-android-build
