test-web-build:
  extends: .build
  only:
    - dev

test-web-deploy:
  extends: .deploy
  dependencies:
    - test-web-build
  only:
    - dev

test-android-build:
  extends: .build-android
  only:
    refs:
      - dev
    variables:
    - $ANDROID_KEYSTORE

test-android-deploy:
  extends: .deploy-android
  dependencies:
    - test-android-build
  rules:
    refs:
      - dev
    variables:
      - $ANDROID_KEYSTORE

