test-web-build:
  extends: .build
  variables:
    BUILD: test
    TAG: latest
  only:
    - dev

test-web-deploy:
  extends: .deploy
  variables:
    TAG: latest
  dependencies:
    - test-web-build
  only:
    - dev

