image: docker:latest
service:
  - docker:dind
before_script:
  - apk add --update curl bash python3
  - curl https://sdk.cloud.google.com | CLOUDSDK_CORE_DISABLE_PROMPTS=1 bash
  - export PATH=$PATH:/root/google-cloud-sdk/bin/
  - echo $GCP_SERVICE_ACCOUNT > /root/key.json
  - gcloud auth activate-service-account --key-file /root/key.json
  - gcloud auth configure-docker --quiet
  - docker login -u _json_key --password-stdin https://asia.gcr.io < /root/key.json
