image: docker:stable
services:
  - docker:stable-dind

before_script:
  - echo $GCP_SERVICE_ACCOUNT > /root/key.json
  - docker login -u _json_key --password-stdin https://asia.gcr.io < /root/key.json
  - rm -rf /root/key.json
