.android-rule: &android-rule
  rules:
    - if: $CI_COMMIT_BRANCH == $BANCH
    - if: $ANDROID_KEYSTORE != null

.release-branch: &release-branch
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\/\d+\.\d+$/
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/

.release-android: &release-android
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\/\d+\.\d+$/
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
    - if: $ANDROID_KEYSTORE != null

.commit-branch: &commit-branch
  rules:
    if: $CI_COMMIT_BRANCH == $BANCH

.android: &android
  variables:
    APP_ENV: android

.build:
  stage: build
  script:
    - docker build . -t $DOCKER_IMAGE_REPO:$TAG --build-arg BUILD=$BUILD --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA
    - docker save $DOCKER_IMAGE_REPO:$TAG > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 day
  <<: *commit-branch

.deploy:
  stage: deploy
  script:
    - docker load < image.tar
  after_script:
    - docker push $DOCKER_IMAGE_REPO:$TAG
  <<: *commit-branch

.prod-build:
  extends: .build
  <<: *release-branch

.prod-deploy:
  extends: .deploy
  <<: *release-branch

.build-android:
  extends:
    - .build
  <<: *android
  script:
    - docker build . -t $DOCKER_IMAGE_REPO:$TAG --build-arg ANDROID_ALIAS=${ANDROID_ALIAS} --build-arg ANDROID_STORE_PASSWORD=${ANDROID_STORE_PASSWORD} --build-args ANDROID_KEYSTORE=${ANDROID_KEYSTORE} --build-arg BUILD=${BUILD} --build-arg APP_ENV=android
    - docker save $DOCKER_IMAGE_REPO:$TAG > image.tar
  <<: *android-rule

.deploy-android:
  extends:
    - .deploy
  <<: *android
  after_script:
    - ID=$(docker create $DOCKER_IMAGE_REPO:$TAG)
    - docker cp $ID:/app/platforms/android/app/build/outputs/apk/debug/apk-debug.apk .
    - docker rm -f $ID
    # cp apk to google cloud storage
  <<: *android-rule

.prod-build-android:
  extends: .build-android
  <<: *release-android

.prod-deploy-android:
  extends: .deploy-android  
  <<: *release-android
